flowchart LR
    P[Proyecto Flutter] --> A[pubspec.yaml]
    P --> B[analysis_options.yaml]
    P --> C[web]
    P --> D[lib]
    D --> E[core/network/api_client.dart]
    D --> F[core/routes/app_router.dart]
    D --> G[shared/themes/app_theme.dart]
    D --> H[modules]
    H --> I[entidad_model.dart]
    H --> J[entidad_service.dart]
    H --> K[entidad_provider.dart]
    H --> L[entidad_list_screen.dart]
    H --> M[entidad_form_screen.dart]
