"""initial persistence model

Revision ID: 3984b20ad386
Revises: 
Create Date: 2026-09-07 06:29:45.213409
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3984b20ad386'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_access_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=80), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('module', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_module'), 'audit_logs', ['module'], unique=False)
    op.create_table('project_invitations',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=False),
    sa.Column('invited_user_id', sa.UUID(), nullable=True),
    sa.Column('invited_email', sa.String(length=180), nullable=False),
    sa.Column('project_role', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_invitations_invited_email'), 'project_invitations', ['invited_email'], unique=False)
    op.create_index(op.f('ix_project_invitations_project_id'), 'project_invitations', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_invitations_status'), 'project_invitations', ['status'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_role', sa.String(length=40), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_members_project_user')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_project_role'), 'project_members', ['project_role'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('project_versions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_number', name='uq_project_versions_project_number')
    )
    op.create_index(op.f('ix_project_versions_project_id'), 'project_versions', ['project_id'], unique=False)
    op.create_table('uml_diagrams',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('diagram_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uml_diagrams_project_id'), 'uml_diagrams', ['project_id'], unique=False)
    op.create_index(op.f('ix_uml_diagrams_status'), 'uml_diagrams', ['status'], unique=False)
    op.create_table('ai_processes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('diagram_id', sa.UUID(), nullable=True),
    sa.Column('process_type', sa.String(length=80), nullable=False),
    sa.Column('model_provider', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagram_id'], ['uml_diagrams.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_processes_process_type'), 'ai_processes', ['process_type'], unique=False)
    op.create_index(op.f('ix_ai_processes_status'), 'ai_processes', ['status'], unique=False)
    op.create_index(op.f('ix_ai_processes_user_id'), 'ai_processes', ['user_id'], unique=False)
    op.create_table('collaboration_events',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('diagram_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('element_type', sa.String(length=80), nullable=True),
    sa.Column('element_id', sa.UUID(), nullable=True),
    sa.Column('base_version', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagram_id'], ['uml_diagrams.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaboration_events_event_type'), 'collaboration_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_collaboration_events_project_id'), 'collaboration_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_collaboration_events_user_id'), 'collaboration_events', ['user_id'], unique=False)
    op.create_table('project_permissions',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('permission_code', sa.String(length=80), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['project_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'permission_code', name='uq_project_permissions_member_code')
    )
    op.create_index(op.f('ix_project_permissions_member_id'), 'project_permissions', ['member_id'], unique=False)
    op.create_index(op.f('ix_project_permissions_permission_code'), 'project_permissions', ['permission_code'], unique=False)
    op.create_table('uml_classes',
    sa.Column('diagram_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('element_type', sa.String(length=40), nullable=False),
    sa.Column('stereotype', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagram_id'], ['uml_diagrams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uml_classes_diagram_id'), 'uml_classes', ['diagram_id'], unique=False)
    op.create_index(op.f('ix_uml_classes_name'), 'uml_classes', ['name'], unique=False)
    op.create_table('uml_transformations',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('diagram_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=False),
    sa.Column('source_version', sa.String(length=80), nullable=True),
    sa.Column('target_platform', sa.String(length=80), nullable=False),
    sa.Column('intermediate_model', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagram_id'], ['uml_diagrams.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uml_transformations_diagram_id'), 'uml_transformations', ['diagram_id'], unique=False)
    op.create_index(op.f('ix_uml_transformations_project_id'), 'uml_transformations', ['project_id'], unique=False)
    op.create_index(op.f('ix_uml_transformations_requested_by_user_id'), 'uml_transformations', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_uml_transformations_status'), 'uml_transformations', ['status'], unique=False)
    op.create_table('uml_visual_elements',
    sa.Column('diagram_id', sa.UUID(), nullable=False),
    sa.Column('element_type', sa.String(length=50), nullable=False),
    sa.Column('element_id', sa.UUID(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('style', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagram_id'], ['uml_diagrams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagram_id', 'element_type', 'element_id', name='uq_visual_element_ref')
    )
    op.create_index(op.f('ix_uml_visual_elements_diagram_id'), 'uml_visual_elements', ['diagram_id'], unique=False)
    op.create_table('xmi_exchanges',
    sa.Column('diagram_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exchange_type', sa.String(length=30), nullable=False),
    sa.Column('tool_name', sa.String(length=120), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagram_id'], ['uml_diagrams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xmi_exchanges_diagram_id'), 'xmi_exchanges', ['diagram_id'], unique=False)
    op.create_index(op.f('ix_xmi_exchanges_exchange_type'), 'xmi_exchanges', ['exchange_type'], unique=False)
    op.create_index(op.f('ix_xmi_exchanges_status'), 'xmi_exchanges', ['status'], unique=False)
    op.create_index(op.f('ix_xmi_exchanges_user_id'), 'xmi_exchanges', ['user_id'], unique=False)
    op.create_table('generated_backends',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('transformation_id', sa.UUID(), nullable=False),
    sa.Column('generated_by_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('technology', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('database_engine', sa.String(length=80), nullable=False),
    sa.Column('version_label', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['transformation_id'], ['uml_transformations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_backends_generated_by_user_id'), 'generated_backends', ['generated_by_user_id'], unique=False)
    op.create_index(op.f('ix_generated_backends_project_id'), 'generated_backends', ['project_id'], unique=False)
    op.create_index(op.f('ix_generated_backends_status'), 'generated_backends', ['status'], unique=False)
    op.create_index(op.f('ix_generated_backends_transformation_id'), 'generated_backends', ['transformation_id'], unique=False)
    op.create_table('uml_attributes',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('data_type', sa.String(length=120), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('initial_value', sa.String(length=255), nullable=True),
    sa.Column('multiplicity', sa.String(length=40), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['uml_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uml_attributes_class_id'), 'uml_attributes', ['class_id'], unique=False)
    op.create_table('uml_methods',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('return_type', sa.String(length=120), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['uml_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uml_methods_class_id'), 'uml_methods', ['class_id'], unique=False)
    op.create_table('uml_relationships',
    sa.Column('diagram_id', sa.UUID(), nullable=False),
    sa.Column('source_class_id', sa.UUID(), nullable=False),
    sa.Column('target_class_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('source_cardinality', sa.String(length=40), nullable=True),
    sa.Column('target_cardinality', sa.String(length=40), nullable=True),
    sa.Column('direction', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagram_id'], ['uml_diagrams.id'], ),
    sa.ForeignKeyConstraint(['source_class_id'], ['uml_classes.id'], ),
    sa.ForeignKeyConstraint(['target_class_id'], ['uml_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uml_relationships_diagram_id'), 'uml_relationships', ['diagram_id'], unique=False)
    op.create_index(op.f('ix_uml_relationships_relationship_type'), 'uml_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_uml_relationships_source_class_id'), 'uml_relationships', ['source_class_id'], unique=False)
    op.create_index(op.f('ix_uml_relationships_target_class_id'), 'uml_relationships', ['target_class_id'], unique=False)
    op.create_table('generated_frontends',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('transformation_id', sa.UUID(), nullable=False),
    sa.Column('generated_by_user_id', sa.UUID(), nullable=False),
    sa.Column('backend_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('technology', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('version_label', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['backend_id'], ['generated_backends.id'], ),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['transformation_id'], ['uml_transformations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_frontends_generated_by_user_id'), 'generated_frontends', ['generated_by_user_id'], unique=False)
    op.create_index(op.f('ix_generated_frontends_project_id'), 'generated_frontends', ['project_id'], unique=False)
    op.create_index(op.f('ix_generated_frontends_status'), 'generated_frontends', ['status'], unique=False)
    op.create_index(op.f('ix_generated_frontends_transformation_id'), 'generated_frontends', ['transformation_id'], unique=False)
    op.create_table('uml_parameters',
    sa.Column('method_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('data_type', sa.String(length=120), nullable=False),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['method_id'], ['uml_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uml_parameters_method_id'), 'uml_parameters', ['method_id'], unique=False)
    op.create_table('generated_artifacts',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('generated_backend_id', sa.UUID(), nullable=True),
    sa.Column('generated_frontend_id', sa.UUID(), nullable=True),
    sa.Column('artifact_type', sa.String(length=60), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_backend_id'], ['generated_backends.id'], ),
    sa.ForeignKeyConstraint(['generated_frontend_id'], ['generated_frontends.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_artifacts_artifact_type'), 'generated_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_generated_artifacts_project_id'), 'generated_artifacts', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_artifacts_project_id'), table_name='generated_artifacts')
    op.drop_index(op.f('ix_generated_artifacts_artifact_type'), table_name='generated_artifacts')
    op.drop_table('generated_artifacts')
    op.drop_index(op.f('ix_uml_parameters_method_id'), table_name='uml_parameters')
    op.drop_table('uml_parameters')
    op.drop_index(op.f('ix_generated_frontends_transformation_id'), table_name='generated_frontends')
    op.drop_index(op.f('ix_generated_frontends_status'), table_name='generated_frontends')
    op.drop_index(op.f('ix_generated_frontends_project_id'), table_name='generated_frontends')
    op.drop_index(op.f('ix_generated_frontends_generated_by_user_id'), table_name='generated_frontends')
    op.drop_table('generated_frontends')
    op.drop_index(op.f('ix_uml_relationships_target_class_id'), table_name='uml_relationships')
    op.drop_index(op.f('ix_uml_relationships_source_class_id'), table_name='uml_relationships')
    op.drop_index(op.f('ix_uml_relationships_relationship_type'), table_name='uml_relationships')
    op.drop_index(op.f('ix_uml_relationships_diagram_id'), table_name='uml_relationships')
    op.drop_table('uml_relationships')
    op.drop_index(op.f('ix_uml_methods_class_id'), table_name='uml_methods')
    op.drop_table('uml_methods')
    op.drop_index(op.f('ix_uml_attributes_class_id'), table_name='uml_attributes')
    op.drop_table('uml_attributes')
    op.drop_index(op.f('ix_generated_backends_transformation_id'), table_name='generated_backends')
    op.drop_index(op.f('ix_generated_backends_status'), table_name='generated_backends')
    op.drop_index(op.f('ix_generated_backends_project_id'), table_name='generated_backends')
    op.drop_index(op.f('ix_generated_backends_generated_by_user_id'), table_name='generated_backends')
    op.drop_table('generated_backends')
    op.drop_index(op.f('ix_xmi_exchanges_user_id'), table_name='xmi_exchanges')
    op.drop_index(op.f('ix_xmi_exchanges_status'), table_name='xmi_exchanges')
    op.drop_index(op.f('ix_xmi_exchanges_exchange_type'), table_name='xmi_exchanges')
    op.drop_index(op.f('ix_xmi_exchanges_diagram_id'), table_name='xmi_exchanges')
    op.drop_table('xmi_exchanges')
    op.drop_index(op.f('ix_uml_visual_elements_diagram_id'), table_name='uml_visual_elements')
    op.drop_table('uml_visual_elements')
    op.drop_index(op.f('ix_uml_transformations_status'), table_name='uml_transformations')
    op.drop_index(op.f('ix_uml_transformations_requested_by_user_id'), table_name='uml_transformations')
    op.drop_index(op.f('ix_uml_transformations_project_id'), table_name='uml_transformations')
    op.drop_index(op.f('ix_uml_transformations_diagram_id'), table_name='uml_transformations')
    op.drop_table('uml_transformations')
    op.drop_index(op.f('ix_uml_classes_name'), table_name='uml_classes')
    op.drop_index(op.f('ix_uml_classes_diagram_id'), table_name='uml_classes')
    op.drop_table('uml_classes')
    op.drop_index(op.f('ix_project_permissions_permission_code'), table_name='project_permissions')
    op.drop_index(op.f('ix_project_permissions_member_id'), table_name='project_permissions')
    op.drop_table('project_permissions')
    op.drop_index(op.f('ix_collaboration_events_user_id'), table_name='collaboration_events')
    op.drop_index(op.f('ix_collaboration_events_project_id'), table_name='collaboration_events')
    op.drop_index(op.f('ix_collaboration_events_event_type'), table_name='collaboration_events')
    op.drop_table('collaboration_events')
    op.drop_index(op.f('ix_ai_processes_user_id'), table_name='ai_processes')
    op.drop_index(op.f('ix_ai_processes_status'), table_name='ai_processes')
    op.drop_index(op.f('ix_ai_processes_process_type'), table_name='ai_processes')
    op.drop_table('ai_processes')
    op.drop_index(op.f('ix_uml_diagrams_status'), table_name='uml_diagrams')
    op.drop_index(op.f('ix_uml_diagrams_project_id'), table_name='uml_diagrams')
    op.drop_table('uml_diagrams')
    op.drop_index(op.f('ix_project_versions_project_id'), table_name='project_versions')
    op.drop_table('project_versions')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_role'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_project_invitations_status'), table_name='project_invitations')
    op.drop_index(op.f('ix_project_invitations_project_id'), table_name='project_invitations')
    op.drop_index(op.f('ix_project_invitations_invited_email'), table_name='project_invitations')
    op.drop_table('project_invitations')
    op.drop_index(op.f('ix_audit_logs_module'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###

